//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5420
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Framework.Common.ResourceManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class i18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal i18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Framework.Common.ResourceManager.i18n", typeof(i18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load spare cargo. Please select another one..
        /// </summary>
        internal static string HAC101_0001 {
            get {
                return ResourceManager.GetString("HAC101_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item was added..
        /// </summary>
        internal static string HAC103_0001 {
            get {
                return ResourceManager.GetString("HAC103_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Arrival Time should be within Workdate and Shift..
        /// </summary>
        internal static string HAC103_0002 {
            get {
                return ResourceManager.GetString("HAC103_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo was already loaded. Please select another one..
        /// </summary>
        internal static string HAC105_0001 {
            get {
                return ResourceManager.GetString("HAC105_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping note is not confirmed. This cargo cannot load..
        /// </summary>
        internal static string HAC105_0002 {
            get {
                return ResourceManager.GetString("HAC105_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input end time in case of Return to shipper..
        /// </summary>
        internal static string HAC105_0003 {
            get {
                return ResourceManager.GetString("HAC105_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input lorry number in case of Return to shipper..
        /// </summary>
        internal static string HAC105_0004 {
            get {
                return ResourceManager.GetString("HAC105_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to auto deallocate ?.
        /// </summary>
        internal static string HAC105_0005 {
            get {
                return ResourceManager.GetString("HAC105_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading break bulk: Act MT and QTY must be greater than 0..
        /// </summary>
        internal static string HAC105_0006 {
            get {
                return ResourceManager.GetString("HAC105_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading cancel amount must be equal or less than Act amount..
        /// </summary>
        internal static string HAC105_0007 {
            get {
                return ResourceManager.GetString("HAC105_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Shut-out location..
        /// </summary>
        internal static string HAC105_0008 {
            get {
                return ResourceManager.GetString("HAC105_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Damage location..
        /// </summary>
        internal static string HAC105_0009 {
            get {
                return ResourceManager.GetString("HAC105_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input MT and QTY in case of break bulk..
        /// </summary>
        internal static string HAC105_0010 {
            get {
                return ResourceManager.GetString("HAC105_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input MT in case of dry bulk..
        /// </summary>
        internal static string HAC105_0011 {
            get {
                return ResourceManager.GetString("HAC105_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input MT in case of dry bulk..
        /// </summary>
        internal static string HAC105_0012 {
            get {
                return ResourceManager.GetString("HAC105_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading dry bulk: Act MT must be greater than 0..
        /// </summary>
        internal static string HAC105_0013 {
            get {
                return ResourceManager.GetString("HAC105_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input lorry number..
        /// </summary>
        internal static string HAC105_0014 {
            get {
                return ResourceManager.GetString("HAC105_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Loose Bag Type in case there exists Loose Bag Amount..
        /// </summary>
        internal static string HAC105_0015 {
            get {
                return ResourceManager.GetString("HAC105_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Loose Bag Amount in case there exists Loose Bag Type..
        /// </summary>
        internal static string HAC105_0016 {
            get {
                return ResourceManager.GetString("HAC105_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve inputted in both loading normal fields and loading cancel fields. All of these will be recored. Do you really want to continue ?.
        /// </summary>
        internal static string HAC105_0017 {
            get {
                return ResourceManager.GetString("HAC105_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo was already discharged. Please select another one..
        /// </summary>
        internal static string HAC106_0001 {
            get {
                return ResourceManager.GetString("HAC106_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance is zero. If this is over-landed amount, please select Indirect radio button and tick on Over-landed check box..
        /// </summary>
        internal static string HAC106_0002 {
            get {
                return ResourceManager.GetString("HAC106_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please tick on Over-landed check box..
        /// </summary>
        internal static string HAC106_0003 {
            get {
                return ResourceManager.GetString("HAC106_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery type is indirect. Please select Indirect radio button to proceed..
        /// </summary>
        internal static string HAC106_0004 {
            get {
                return ResourceManager.GetString("HAC106_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input lorry number..
        /// </summary>
        internal static string HAC106_0005 {
            get {
                return ResourceManager.GetString("HAC106_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/O is not exist. This cargo cannot discharge..
        /// </summary>
        internal static string HAC106_0006 {
            get {
                return ResourceManager.GetString("HAC106_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery type is direct. If this is over-landed amount, please tick on Over-landed check box..
        /// </summary>
        internal static string HAC106_0007 {
            get {
                return ResourceManager.GetString("HAC106_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actutal amount should not exceed balance amount. If this is over-landed amount, please tick on Over-landed checkbox..
        /// </summary>
        internal static string HAC106_0008 {
            get {
                return ResourceManager.GetString("HAC106_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is short-landed cargo. Do you want to save ?.
        /// </summary>
        internal static string HAC106_0009 {
            get {
                return ResourceManager.GetString("HAC106_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no permission of this cargo from customs. Do you want to go proceed to discharge ?.
        /// </summary>
        internal static string HAC106_0010 {
            get {
                return ResourceManager.GetString("HAC106_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBK cargo, Actual Qty has to be greater than 0, please re-input the amount..
        /// </summary>
        internal static string HAC106_0011 {
            get {
                return ResourceManager.GetString("HAC106_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input lorry number..
        /// </summary>
        internal static string HAC112_0001 {
            get {
                return ResourceManager.GetString("HAC112_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Loose Bag Type in case there exists Loose Bag Amount..
        /// </summary>
        internal static string HAC112_0002 {
            get {
                return ResourceManager.GetString("HAC112_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Loose Bag Amount in case there exists Loose Bag Type..
        /// </summary>
        internal static string HAC112_0003 {
            get {
                return ResourceManager.GetString("HAC112_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input GR number.
        /// </summary>
        internal static string HCM00001111 {
            get {
                return ResourceManager.GetString("HCM00001111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input DO number.
        /// </summary>
        internal static string HCM00001112 {
            get {
                return ResourceManager.GetString("HCM00001112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input GP number.
        /// </summary>
        internal static string HCM00001113 {
            get {
                return ResourceManager.GetString("HCM00001113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string HCM0001 {
            get {
                return ResourceManager.GetString("HCM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string HCM0002 {
            get {
                return ResourceManager.GetString("HCM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string HCM0003 {
            get {
                return ResourceManager.GetString("HCM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        internal static string HCM0004 {
            get {
                return ResourceManager.GetString("HCM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        internal static string HCM0005 {
            get {
                return ResourceManager.GetString("HCM0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string HCM0006 {
            get {
                return ResourceManager.GetString("HCM0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program Exit.
        /// </summary>
        internal static string HCM0007 {
            get {
                return ResourceManager.GetString("HCM0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string HCM0008 {
            get {
                return ResourceManager.GetString("HCM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLUS Member LogIn.
        /// </summary>
        internal static string HCM0009 {
            get {
                return ResourceManager.GetString("HCM0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string HCM0010 {
            get {
                return ResourceManager.GetString("HCM0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goto.
        /// </summary>
        internal static string HCM0011 {
            get {
                return ResourceManager.GetString("HCM0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Message.
        /// </summary>
        internal static string HCM0012 {
            get {
                return ResourceManager.GetString("HCM0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string HCM0013 {
            get {
                return ResourceManager.GetString("HCM0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string HCM0014 {
            get {
                return ResourceManager.GetString("HCM0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string HCM0015 {
            get {
                return ResourceManager.GetString("HCM0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string HCM0016 {
            get {
                return ResourceManager.GetString("HCM0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F1.
        /// </summary>
        internal static string HCM0017 {
            get {
                return ResourceManager.GetString("HCM0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F2.
        /// </summary>
        internal static string HCM0018 {
            get {
                return ResourceManager.GetString("HCM0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F3.
        /// </summary>
        internal static string HCM0019 {
            get {
                return ResourceManager.GetString("HCM0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F4.
        /// </summary>
        internal static string HCM0020 {
            get {
                return ResourceManager.GetString("HCM0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F5.
        /// </summary>
        internal static string HCM0021 {
            get {
                return ResourceManager.GetString("HCM0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F6.
        /// </summary>
        internal static string HCM0022 {
            get {
                return ResourceManager.GetString("HCM0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F7.
        /// </summary>
        internal static string HCM0023 {
            get {
                return ResourceManager.GetString("HCM0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F8.
        /// </summary>
        internal static string HCM0024 {
            get {
                return ResourceManager.GetString("HCM0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F9.
        /// </summary>
        internal static string HCM0025 {
            get {
                return ResourceManager.GetString("HCM0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string HCM0026 {
            get {
                return ResourceManager.GetString("HCM0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JPVC number..
        /// </summary>
        internal static string HCM0027 {
            get {
                return ResourceManager.GetString("HCM0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid S/N number..
        /// </summary>
        internal static string HCM0028 {
            get {
                return ResourceManager.GetString("HCM0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid G/R number..
        /// </summary>
        internal static string HCM0029 {
            get {
                return ResourceManager.GetString("HCM0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid B/L number..
        /// </summary>
        internal static string HCM0030 {
            get {
                return ResourceManager.GetString("HCM0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid D/O number..
        /// </summary>
        internal static string HCM0031 {
            get {
                return ResourceManager.GetString("HCM0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Lorry number..
        /// </summary>
        internal static string HCM0032 {
            get {
                return ResourceManager.GetString("HCM0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid G/P number..
        /// </summary>
        internal static string HCM0033 {
            get {
                return ResourceManager.GetString("HCM0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid driver number..
        /// </summary>
        internal static string HCM0034 {
            get {
                return ResourceManager.GetString("HCM0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid stevedore company..
        /// </summary>
        internal static string HCM0035 {
            get {
                return ResourceManager.GetString("HCM0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid trimming company..
        /// </summary>
        internal static string HCM0036 {
            get {
                return ResourceManager.GetString("HCM0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid delay code..
        /// </summary>
        internal static string HCM0037 {
            get {
                return ResourceManager.GetString("HCM0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid contractor..
        /// </summary>
        internal static string HCM0038 {
            get {
                return ResourceManager.GetString("HCM0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid requester..
        /// </summary>
        internal static string HCM0039 {
            get {
                return ResourceManager.GetString("HCM0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid commodity..
        /// </summary>
        internal static string HCM0040 {
            get {
                return ResourceManager.GetString("HCM0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTime should be less than EndTime..
        /// </summary>
        internal static string HCM0041 {
            get {
                return ResourceManager.GetString("HCM0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order of DateTime. It should be ATB &lt; ATW &lt; ATC &lt; ATU..
        /// </summary>
        internal static string HCM0042 {
            get {
                return ResourceManager.GetString("HCM0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order of DateTime. It should be ETB &lt; ETW &lt; ETC &lt; ETU..
        /// </summary>
        internal static string HCM0043 {
            get {
                return ResourceManager.GetString("HCM0043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order of DateTime. It should be Hose On &lt; Commence &lt; Completion &lt; Hose Off Time..
        /// </summary>
        internal static string HCM0044 {
            get {
                return ResourceManager.GetString("HCM0044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data already exist. Please check again..
        /// </summary>
        internal static string HCM0045 {
            get {
                return ResourceManager.GetString("HCM0045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this item ?.
        /// </summary>
        internal static string HCM0046 {
            get {
                return ResourceManager.GetString("HCM0046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License has expired. Allow to continue ?.
        /// </summary>
        internal static string HCM0047 {
            get {
                return ResourceManager.GetString("HCM0047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully.
        /// </summary>
        internal static string HCM0048 {
            get {
                return ResourceManager.GetString("HCM0048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select JPVC.
        /// </summary>
        internal static string HCM0049 {
            get {
                return ResourceManager.GetString("HCM0049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select GR.
        /// </summary>
        internal static string HCM0050 {
            get {
                return ResourceManager.GetString("HCM0050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select BL.
        /// </summary>
        internal static string HCM0051 {
            get {
                return ResourceManager.GetString("HCM0051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select BL/DO.
        /// </summary>
        internal static string HCM0052 {
            get {
                return ResourceManager.GetString("HCM0052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select DO.
        /// </summary>
        internal static string HCM0053 {
            get {
                return ResourceManager.GetString("HCM0053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select GP.
        /// </summary>
        internal static string HCM0054 {
            get {
                return ResourceManager.GetString("HCM0054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select Lorry..
        /// </summary>
        internal static string HCM0055 {
            get {
                return ResourceManager.GetString("HCM0055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input/select transporter.
        /// </summary>
        internal static string HCM0056 {
            get {
                return ResourceManager.GetString("HCM0056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string HCM0057 {
            get {
                return ResourceManager.GetString("HCM0057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data. Please try again..
        /// </summary>
        internal static string HCM0058 {
            get {
                return ResourceManager.GetString("HCM0058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time and End Time should be within Work Date and Shift.
        /// </summary>
        internal static string HCM0059 {
            get {
                return ResourceManager.GetString("HCM0059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a mandatory item.
        /// </summary>
        internal static string HCM0060 {
            get {
                return ResourceManager.GetString("HCM0060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes NOT saved. Commit changes ?.
        /// </summary>
        internal static string HCM0061 {
            get {
                return ResourceManager.GetString("HCM0061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        internal static string HCM0062 {
            get {
                return ResourceManager.GetString("HCM0062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string HCM0063 {
            get {
                return ResourceManager.GetString("HCM0063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this confirm final loading ?.
        /// </summary>
        internal static string HCM0064 {
            get {
                return ResourceManager.GetString("HCM0064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this final discharging ?.
        /// </summary>
        internal static string HCM0065 {
            get {
                return ResourceManager.GetString("HCM0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this final Handling-In ?.
        /// </summary>
        internal static string HCM0066 {
            get {
                return ResourceManager.GetString("HCM0066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this final Handling-Out ?.
        /// </summary>
        internal static string HCM0067 {
            get {
                return ResourceManager.GetString("HCM0067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this final Rehandle Loading ?.
        /// </summary>
        internal static string HCM0068 {
            get {
                return ResourceManager.GetString("HCM0068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this final Rehandle Handling-Out ?.
        /// </summary>
        internal static string HCM0069 {
            get {
                return ResourceManager.GetString("HCM0069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid package type..
        /// </summary>
        internal static string HCM0070 {
            get {
                return ResourceManager.GetString("HCM0070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid loose bag type..
        /// </summary>
        internal static string HCM0071 {
            get {
                return ResourceManager.GetString("HCM0071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successfully. Do you want to print Gate Pass for GP_no .
        /// </summary>
        internal static string HCM0072 {
            get {
                return ResourceManager.GetString("HCM0072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT / M3 / QTY must be greater then 0 .
        /// </summary>
        internal static string HCM0073 {
            get {
                return ResourceManager.GetString("HCM0073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry and Driver must belong to the same Transport Company..
        /// </summary>
        internal static string HCM0074 {
            get {
                return ResourceManager.GetString("HCM0074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be final loading, Please check final..
        /// </summary>
        internal static string HCM0075 {
            get {
                return ResourceManager.GetString("HCM0075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will be final handling, Please check final..
        /// </summary>
        internal static string HCM0076 {
            get {
                return ResourceManager.GetString("HCM0076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM101_0001 {
            get {
                return ResourceManager.GetString("HCM101_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Name.
        /// </summary>
        internal static string HCM101_0002 {
            get {
                return ResourceManager.GetString("HCM101_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETB.
        /// </summary>
        internal static string HCM101_0003 {
            get {
                return ResourceManager.GetString("HCM101_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berth Location.
        /// </summary>
        internal static string HCM101_0004 {
            get {
                return ResourceManager.GetString("HCM101_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOA.
        /// </summary>
        internal static string HCM101_0005 {
            get {
                return ResourceManager.GetString("HCM101_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATB.
        /// </summary>
        internal static string HCM101_0006 {
            get {
                return ResourceManager.GetString("HCM101_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETW.
        /// </summary>
        internal static string HCM101_0007 {
            get {
                return ResourceManager.GetString("HCM101_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wharfStart.
        /// </summary>
        internal static string HCM101_0008 {
            get {
                return ResourceManager.GetString("HCM101_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wharfEnd.
        /// </summary>
        internal static string HCM101_0009 {
            get {
                return ResourceManager.GetString("HCM101_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATW.
        /// </summary>
        internal static string HCM101_0010 {
            get {
                return ResourceManager.GetString("HCM101_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETC.
        /// </summary>
        internal static string HCM101_0011 {
            get {
                return ResourceManager.GetString("HCM101_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATC.
        /// </summary>
        internal static string HCM101_0012 {
            get {
                return ResourceManager.GetString("HCM101_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ETU.
        /// </summary>
        internal static string HCM101_0013 {
            get {
                return ResourceManager.GetString("HCM101_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATU.
        /// </summary>
        internal static string HCM101_0014 {
            get {
                return ResourceManager.GetString("HCM101_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel.
        /// </summary>
        internal static string HCM101_0015 {
            get {
                return ResourceManager.GetString("HCM101_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsl Type.
        /// </summary>
        internal static string HCM101_0016 {
            get {
                return ResourceManager.GetString("HCM101_0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vsl Type Name.
        /// </summary>
        internal static string HCM101_0017 {
            get {
                return ResourceManager.GetString("HCM101_0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Delay Code.
        /// </summary>
        internal static string HCM102_0001 {
            get {
                return ResourceManager.GetString("HCM102_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Code.
        /// </summary>
        internal static string HCM102_0002 {
            get {
                return ResourceManager.GetString("HCM102_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string HCM102_0003 {
            get {
                return ResourceManager.GetString("HCM102_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string HCM102_0004 {
            get {
                return ResourceManager.GetString("HCM102_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted Delay.
        /// </summary>
        internal static string HCM102_0005 {
            get {
                return ResourceManager.GetString("HCM102_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR List.
        /// </summary>
        internal static string HCM103_0001 {
            get {
                return ResourceManager.GetString("HCM103_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM103_0002 {
            get {
                return ResourceManager.GetString("HCM103_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN No.
        /// </summary>
        internal static string HCM103_0003 {
            get {
                return ResourceManager.GetString("HCM103_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR No.
        /// </summary>
        internal static string HCM103_0004 {
            get {
                return ResourceManager.GetString("HCM103_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G/R.
        /// </summary>
        internal static string HCM103_0005 {
            get {
                return ResourceManager.GetString("HCM103_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry.
        /// </summary>
        internal static string HCM103_0006 {
            get {
                return ResourceManager.GetString("HCM103_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        internal static string HCM103_0007 {
            get {
                return ResourceManager.GetString("HCM103_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string HCM103_0008 {
            get {
                return ResourceManager.GetString("HCM103_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.
        /// </summary>
        internal static string HCM103_0009 {
            get {
                return ResourceManager.GetString("HCM103_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HCM103_0010 {
            get {
                return ResourceManager.GetString("HCM103_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/L List.
        /// </summary>
        internal static string HCM104_0001 {
            get {
                return ResourceManager.GetString("HCM104_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM104_0002 {
            get {
                return ResourceManager.GetString("HCM104_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL NO.
        /// </summary>
        internal static string HCM104_0003 {
            get {
                return ResourceManager.GetString("HCM104_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/L.
        /// </summary>
        internal static string HCM104_0004 {
            get {
                return ResourceManager.GetString("HCM104_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/O.
        /// </summary>
        internal static string HCM104_0005 {
            get {
                return ResourceManager.GetString("HCM104_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string HCM104_0006 {
            get {
                return ResourceManager.GetString("HCM104_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.
        /// </summary>
        internal static string HCM104_0007 {
            get {
                return ResourceManager.GetString("HCM104_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        internal static string HCM104_0008 {
            get {
                return ResourceManager.GetString("HCM104_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HCM104_0009 {
            get {
                return ResourceManager.GetString("HCM104_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shpr/Cnsne.
        /// </summary>
        internal static string HCM104_0010 {
            get {
                return ResourceManager.GetString("HCM104_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPB Driver List.
        /// </summary>
        internal static string HCM105_0001 {
            get {
                return ResourceManager.GetString("HCM105_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Name.
        /// </summary>
        internal static string HCM105_0002 {
            get {
                return ResourceManager.GetString("HCM105_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver ID.
        /// </summary>
        internal static string HCM105_0003 {
            get {
                return ResourceManager.GetString("HCM105_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HCM105_0004 {
            get {
                return ResourceManager.GetString("HCM105_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPB.
        /// </summary>
        internal static string HCM106_0001 {
            get {
                return ResourceManager.GetString("HCM106_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string HCM106_0002 {
            get {
                return ResourceManager.GetString("HCM106_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string HCM106_0003 {
            get {
                return ResourceManager.GetString("HCM106_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        internal static string HCM106_0004 {
            get {
                return ResourceManager.GetString("HCM106_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HCM106_0005 {
            get {
                return ResourceManager.GetString("HCM106_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry List.
        /// </summary>
        internal static string HCM107_0001 {
            get {
                return ResourceManager.GetString("HCM107_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM107_0002 {
            get {
                return ResourceManager.GetString("HCM107_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BL.
        /// </summary>
        internal static string HCM107_0003 {
            get {
                return ResourceManager.GetString("HCM107_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        internal static string HCM107_0004 {
            get {
                return ResourceManager.GetString("HCM107_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string HCM107_0005 {
            get {
                return ResourceManager.GetString("HCM107_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SN/BL.
        /// </summary>
        internal static string HCM107_0006 {
            get {
                return ResourceManager.GetString("HCM107_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        internal static string HCM107_0007 {
            get {
                return ResourceManager.GetString("HCM107_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string HCM107_0008 {
            get {
                return ResourceManager.GetString("HCM107_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/O List.
        /// </summary>
        internal static string HCM108_0001 {
            get {
                return ResourceManager.GetString("HCM108_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM108_0002 {
            get {
                return ResourceManager.GetString("HCM108_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DO NO.
        /// </summary>
        internal static string HCM108_0003 {
            get {
                return ResourceManager.GetString("HCM108_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B/L.
        /// </summary>
        internal static string HCM108_0004 {
            get {
                return ResourceManager.GetString("HCM108_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/O.
        /// </summary>
        internal static string HCM108_0005 {
            get {
                return ResourceManager.GetString("HCM108_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string HCM108_0006 {
            get {
                return ResourceManager.GetString("HCM108_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.
        /// </summary>
        internal static string HCM108_0007 {
            get {
                return ResourceManager.GetString("HCM108_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        internal static string HCM108_0008 {
            get {
                return ResourceManager.GetString("HCM108_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string HCM109_0001 {
            get {
                return ResourceManager.GetString("HCM109_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        internal static string HCM109_0002 {
            get {
                return ResourceManager.GetString("HCM109_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string HCM109_0003 {
            get {
                return ResourceManager.GetString("HCM109_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string HCM109_0004 {
            get {
                return ResourceManager.GetString("HCM109_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string HCM109_0005 {
            get {
                return ResourceManager.GetString("HCM109_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge.
        /// </summary>
        internal static string HCM109_0006 {
            get {
                return ResourceManager.GetString("HCM109_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string HCM110_0001 {
            get {
                return ResourceManager.GetString("HCM110_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string HCM110_0002 {
            get {
                return ResourceManager.GetString("HCM110_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mechanical Equipment.
        /// </summary>
        internal static string HCM112_0001 {
            get {
                return ResourceManager.GetString("HCM112_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string HCM112_0002 {
            get {
                return ResourceManager.GetString("HCM112_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQU Type.
        /// </summary>
        internal static string HCM112_0003 {
            get {
                return ResourceManager.GetString("HCM112_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string HCM112_0004 {
            get {
                return ResourceManager.GetString("HCM112_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Area.
        /// </summary>
        internal static string HCM113_0001 {
            get {
                return ResourceManager.GetString("HCM113_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string HCM113_0002 {
            get {
                return ResourceManager.GetString("HCM113_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string HCM113_0003 {
            get {
                return ResourceManager.GetString("HCM113_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR/BL List.
        /// </summary>
        internal static string HCM114_0001 {
            get {
                return ResourceManager.GetString("HCM114_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR/BL.
        /// </summary>
        internal static string HCM114_0002 {
            get {
                return ResourceManager.GetString("HCM114_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM114_0003 {
            get {
                return ResourceManager.GetString("HCM114_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GR/BL.
        /// </summary>
        internal static string HCM114_0004 {
            get {
                return ResourceManager.GetString("HCM114_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MT.
        /// </summary>
        internal static string HCM114_0005 {
            get {
                return ResourceManager.GetString("HCM114_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3.
        /// </summary>
        internal static string HCM114_0006 {
            get {
                return ResourceManager.GetString("HCM114_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QTY.
        /// </summary>
        internal static string HCM114_0007 {
            get {
                return ResourceManager.GetString("HCM114_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string HCM114_0008 {
            get {
                return ResourceManager.GetString("HCM114_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gatepass Print.
        /// </summary>
        internal static string HCM115_0001 {
            get {
                return ResourceManager.GetString("HCM115_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Port.
        /// </summary>
        internal static string HCM115_0002 {
            get {
                return ResourceManager.GetString("HCM115_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        internal static string HCM115_0003 {
            get {
                return ResourceManager.GetString("HCM115_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Settings.
        /// </summary>
        internal static string HCM115_0004 {
            get {
                return ResourceManager.GetString("HCM115_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input JPVC..
        /// </summary>
        internal static string HCM117_0001 {
            get {
                return ResourceManager.GetString("HCM117_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatePass.
        /// </summary>
        internal static string HCM120_0001 {
            get {
                return ResourceManager.GetString("HCM120_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HCM120_0002 {
            get {
                return ResourceManager.GetString("HCM120_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo No.
        /// </summary>
        internal static string HCM120_0003 {
            get {
                return ResourceManager.GetString("HCM120_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        internal static string HCM120_0004 {
            get {
                return ResourceManager.GetString("HCM120_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatePass.
        /// </summary>
        internal static string HCM120_0005 {
            get {
                return ResourceManager.GetString("HCM120_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry No.
        /// </summary>
        internal static string HCM120_0006 {
            get {
                return ResourceManager.GetString("HCM120_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatePass List.
        /// </summary>
        internal static string HCM120_0007 {
            get {
                return ResourceManager.GetString("HCM120_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorry List.
        /// </summary>
        internal static string HCM120_0008 {
            get {
                return ResourceManager.GetString("HCM120_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This GR/BL/GP with/without this Lorry has been confirmed. Do you want to proceed ?.
        /// </summary>
        internal static string HPS101_0001 {
            get {
                return ResourceManager.GetString("HPS101_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This DG cargo has not permitted yet. Do you still want to confirm Gate-In?.
        /// </summary>
        internal static string HPS101_0002 {
            get {
                return ResourceManager.GetString("HPS101_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter at least 3 characters to search Lorry..
        /// </summary>
        internal static string HPS101_0010 {
            get {
                return ResourceManager.GetString("HPS101_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Operator Main.
        /// </summary>
        internal static string HVO101_0001 {
            get {
                return ResourceManager.GetString("HVO101_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPVC.
        /// </summary>
        internal static string HVO101_0002 {
            get {
                return ResourceManager.GetString("HVO101_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        internal static string HVO101_0003 {
            get {
                return ResourceManager.GetString("HVO101_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dry.
        /// </summary>
        internal static string HVO101_0004 {
            get {
                return ResourceManager.GetString("HVO101_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid Operation.
        /// </summary>
        internal static string HVO101_0005 {
            get {
                return ResourceManager.GetString("HVO101_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F/House for Loading.
        /// </summary>
        internal static string HVO101_0006 {
            get {
                return ResourceManager.GetString("HVO101_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F/House for Discharging.
        /// </summary>
        internal static string HVO101_0007 {
            get {
                return ResourceManager.GetString("HVO101_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLA for Loading.
        /// </summary>
        internal static string HVO101_0008 {
            get {
                return ResourceManager.GetString("HVO101_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MLA for Discharging.
        /// </summary>
        internal static string HVO101_0009 {
            get {
                return ResourceManager.GetString("HVO101_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel.
        /// </summary>
        internal static string HVO101_0010 {
            get {
                return ResourceManager.GetString("HVO101_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shifting.
        /// </summary>
        internal static string HVO101_0011 {
            get {
                return ResourceManager.GetString("HVO101_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jetty OPR.
        /// </summary>
        internal static string HVO101_0012 {
            get {
                return ResourceManager.GetString("HVO101_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string HVO101_0013 {
            get {
                return ResourceManager.GetString("HVO101_0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STV.
        /// </summary>
        internal static string HVO101_0014 {
            get {
                return ResourceManager.GetString("HVO101_0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/Banking.
        /// </summary>
        internal static string HVO101_0015 {
            get {
                return ResourceManager.GetString("HVO101_0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Mark End must be greater than sum of Wharf Mark Start and LOA.
        /// </summary>
        internal static string HVO102_0001 {
            get {
                return ResourceManager.GetString("HVO102_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Start must be equal or greater than berth wharf start ({0}).
        /// </summary>
        internal static string HVO102_0002 {
            get {
                return ResourceManager.GetString("HVO102_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf End must be equal or less than berth wharf end ({0}).
        /// </summary>
        internal static string HVO102_0003 {
            get {
                return ResourceManager.GetString("HVO102_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Mark End must be greater than Wharf Mark Start..
        /// </summary>
        internal static string HVO102_0004 {
            get {
                return ResourceManager.GetString("HVO102_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data already exist. When Hatch No is the same, Start and End Time should not be overlaped..
        /// </summary>
        internal static string HVO103_0001 {
            get {
                return ResourceManager.GetString("HVO103_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EQU cannot be blank. .
        /// </summary>
        internal static string HVO104_0001 {
            get {
                return ResourceManager.GetString("HVO104_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Mark To should be greater than sum of Wharf Mark From and LOA.
        /// </summary>
        internal static string HVO105_0001 {
            get {
                return ResourceManager.GetString("HVO105_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Start must be equal or greater than berth wharf start ({0}).
        /// </summary>
        internal static string HVO105_0002 {
            get {
                return ResourceManager.GetString("HVO105_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf End must be equal or less than berth wharf end ({0}).
        /// </summary>
        internal static string HVO105_0003 {
            get {
                return ResourceManager.GetString("HVO105_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wharf Mark To should be greater than Wharf Mark..
        /// </summary>
        internal static string HVO105_0004 {
            get {
                return ResourceManager.GetString("HVO105_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not proceed! You have to unberth at old location first..
        /// </summary>
        internal static string HVO105_1111 {
            get {
                return ResourceManager.GetString("HVO105_1111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time should be followed Prev ATB, Prev ATU, New ATB, ATW, ATC, New ATU..
        /// </summary>
        internal static string HVO105_1112 {
            get {
                return ResourceManager.GetString("HVO105_1112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Hose Off Time when the operation is completed..
        /// </summary>
        internal static string HVO106_0001 {
            get {
                return ResourceManager.GetString("HVO106_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DG for commodity {0} was not confirmed yet. Do you want to proceed it anyway?.
        /// </summary>
        internal static string HVO106_0002 {
            get {
                return ResourceManager.GetString("HVO106_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is this operation commpleted ?.
        /// </summary>
        internal static string HVO106_0003 {
            get {
                return ResourceManager.GetString("HVO106_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Hose On time..
        /// </summary>
        internal static string HVO106_0004 {
            get {
                return ResourceManager.GetString("HVO106_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Commence time..
        /// </summary>
        internal static string HVO106_0005 {
            get {
                return ResourceManager.GetString("HVO106_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input Complete time..
        /// </summary>
        internal static string HVO106_0006 {
            get {
                return ResourceManager.GetString("HVO106_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve inputted Hose Off. Is this operation completed ?.
        /// </summary>
        internal static string HVO106_0007 {
            get {
                return ResourceManager.GetString("HVO106_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hose On should be within shift time..
        /// </summary>
        internal static string HVO106001_0001 {
            get {
                return ResourceManager.GetString("HVO106001_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commence time should be within shift time..
        /// </summary>
        internal static string HVO106001_0002 {
            get {
                return ResourceManager.GetString("HVO106001_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commplete time should be within shift time..
        /// </summary>
        internal static string HVO106001_0003 {
            get {
                return ResourceManager.GetString("HVO106001_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hose Off should be within shift time..
        /// </summary>
        internal static string HVO106001_0004 {
            get {
                return ResourceManager.GetString("HVO106001_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second vessel must be different from mother vessel..
        /// </summary>
        internal static string HVO108_0001 {
            get {
                return ResourceManager.GetString("HVO108_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd ATU must be equal or less than 3rd ATB..
        /// </summary>
        internal static string HVO108_0002 {
            get {
                return ResourceManager.GetString("HVO108_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input JPVC3 information..
        /// </summary>
        internal static string HVO108_0003 {
            get {
                return ResourceManager.GetString("HVO108_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot change ATB because it exists Shifting or Double Banking info..
        /// </summary>
        internal static string HVO110 {
            get {
                return ResourceManager.GetString("HVO110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate should be greater than 0..
        /// </summary>
        internal static string HVO111_0001 {
            get {
                return ResourceManager.GetString("HVO111_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because it&apos;s requested from MSS..
        /// </summary>
        internal static string HVO112_0001 {
            get {
                return ResourceManager.GetString("HVO112_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is double banking info later than this..
        /// </summary>
        internal static string HVO112_0002 {
            get {
                return ResourceManager.GetString("HVO112_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is equipment setting later than this..
        /// </summary>
        internal static string HVO112_0003 {
            get {
                return ResourceManager.GetString("HVO112_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        internal static string HVO112_0004 {
            get {
                return ResourceManager.GetString("HVO112_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEST.
        /// </summary>
        internal static string HVO112_0005 {
            get {
                return ResourceManager.GetString("HVO112_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is STS info..
        /// </summary>
        internal static string HVO114_0001 {
            get {
                return ResourceManager.GetString("HVO114_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is STS info on 2nd vessel..
        /// </summary>
        internal static string HVO114_0002 {
            get {
                return ResourceManager.GetString("HVO114_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is equipment setting info..
        /// </summary>
        internal static string HVO114_0003 {
            get {
                return ResourceManager.GetString("HVO114_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is equipment setting info on 2nd vessel..
        /// </summary>
        internal static string HVO114_0004 {
            get {
                return ResourceManager.GetString("HVO114_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is shifting info later than this..
        /// </summary>
        internal static string HVO114_0005 {
            get {
                return ResourceManager.GetString("HVO114_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is shifting info on 2nd vessel later than this..
        /// </summary>
        internal static string HVO114_0006 {
            get {
                return ResourceManager.GetString("HVO114_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t delete it because there is ATW or ATC..
        /// </summary>
        internal static string HVO114_0007 {
            get {
                return ResourceManager.GetString("HVO114_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set location..
        /// </summary>
        internal static string HWC101_0001 {
            get {
                return ResourceManager.GetString("HWC101_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set location for damage cargo..
        /// </summary>
        internal static string HWC101_0002 {
            get {
                return ResourceManager.GetString("HWC101_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set location for shut-out cargo..
        /// </summary>
        internal static string HWC101_0003 {
            get {
                return ResourceManager.GetString("HWC101_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please unset location..
        /// </summary>
        internal static string HWC101_0004 {
            get {
                return ResourceManager.GetString("HWC101_0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearance status is not RELEASE. Do you want to proceed ?.
        /// </summary>
        internal static string HWC101_0005 {
            get {
                return ResourceManager.GetString("HWC101_0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo cannot handle in because its delivery type is direct..
        /// </summary>
        internal static string HWC101_0006 {
            get {
                return ResourceManager.GetString("HWC101_0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input end time in case of Return to shipper..
        /// </summary>
        internal static string HWC101_0007 {
            get {
                return ResourceManager.GetString("HWC101_0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input lorry number in case of Return to shipper..
        /// </summary>
        internal static string HWC101_0008 {
            get {
                return ResourceManager.GetString("HWC101_0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo can not handle out because D/O number does not exist..
        /// </summary>
        internal static string HWC101_0009 {
            get {
                return ResourceManager.GetString("HWC101_0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo can not handle out because cargo type is Normal and category is export..
        /// </summary>
        internal static string HWC101_0010 {
            get {
                return ResourceManager.GetString("HWC101_0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input handling-out amount..
        /// </summary>
        internal static string HWC101_0011 {
            get {
                return ResourceManager.GetString("HWC101_0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cargo already handled-in. Please select another cargo..
        /// </summary>
        internal static string HWC101_0012 {
            get {
                return ResourceManager.GetString("HWC101_0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actutal amount can not exceed balance amount. Please check again..
        /// </summary>
        internal static string HWC101001_0001 {
            get {
                return ResourceManager.GetString("HWC101001_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cell is unused area. Please select another one..
        /// </summary>
        internal static string HWC101001_0002 {
            get {
                return ResourceManager.GetString("HWC101001_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This cell is rental area. Please select another one..
        /// </summary>
        internal static string HWC101001_0003 {
            get {
                return ResourceManager.GetString("HWC101001_0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual amount cannot exceed stacked amount. Please check again..
        /// </summary>
        internal static string HWC101002_0001 {
            get {
                return ResourceManager.GetString("HWC101002_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total actual amount should not exceed inputted amount. Please check again..
        /// </summary>
        internal static string HWC101002_0002 {
            get {
                return ResourceManager.GetString("HWC101002_0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo movement item does not exist..
        /// </summary>
        internal static string HWC109_0001 {
            get {
                return ResourceManager.GetString("HWC109_0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV Amount is zero. Please check again..
        /// </summary>
        internal static string HWC109_0002 {
            get {
                return ResourceManager.GetString("HWC109_0002", resourceCulture);
            }
        }
    }
}
